### ISSUE TITLE
DefaultSolver / NaiveHeuristic: nondeterministic behaviour and wrong solution

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#42] opened 2017-01-27 09:54 UTC
When calling `at.ac.tuwien.kr.alpha.solver.HanoiTowerTest.testSimple()` (on [testing-hanoi](https://github.com/AntoniusW/Alpha/tree/testing-hanoi) branch) with `DefaultSolver` and deterministic `NaiveHeuristic`, the following can be experienced:

1. Nondeterministic behaviour: Sometimes the solver finds an answer set quickly and returns it (after 87 decisions), sometimes it takes long time and finds no answer set (after 34228 decisions).
2. In the latter case, the result is actually wrong, because there is a solution to the problem.

**Comment by AntoniusW** [comment] 2017-06-02 07:49
The faulty behaviour seems to no longer occur in the current master branch and nondeterminism has also been removed recently. Please verify.

**Comment by rtaupe** [comment] 2017-07-18 07:42
Sorry, cannot confirm.
On my system, the bug still occurs, buth on the current master branch and on  [testing-hanoi](https://github.com/AntoniusW/Alpha/tree/testing-hanoi) after rebasing it on master.
Just the numbers have changed: When successful, the answer set is found after 7086 choices; when unsuccessful, 42207 choices are done.

**Comment by rtaupe** [comment] 2017-11-23 14:59
**Update:** testing-hanoi branch has been rebased on master. The problem still occurs in the _default/naive/alpharoaming/NAIVE_ configuration (but after executinig the test case a few times it seems that the wrong result is now produced always, i.e. nondeterminism in this respect seems to be gone).

**Comment by rtaupe** [comment] 2017-11-27 15:13
It seems that I could isolate the problem a little: When adding either of the facts `noWhere(0,2).`, `where(0,3).` or `diskWhere(0).` to the input, the problem becomes quickly solvable and a correct answer set is found, so the solver seems to have a problem in deriving `noWhere(0,2).` or `where(0,3).` (the third fact can directly be derived from the second one).

**Comment by AntoniusW** [comment] 2017-11-30 09:12
I am getting progress on this, luckily there are two almost identical runs with different configuration (one failing, one not), after I changed a remaining `HashSet` into a `LinkedHashSet` in the grounder. The missing answer set then seems to be caused by the nogood store accidentally forgetting to set the alpha watch when a nogood with certain properties is added. I should have a fix later.

**Comment by AntoniusW** [comment] 2017-12-01 01:21
Merging #109 locally into `testing-hanoi` should fix the issue with `testSimple()` and also remove another source of non-determinism. Please check if this indeed fixes all of the problems raised in this issue.

Btw, for some of our other test cases on `master` the alpha watch was also lost, but this did not show up in the computation results.

**Comment by lorenzleutgeb** [comment] 2017-12-02 12:15
I rebased a copy of `testing-hanoi` onto `issue_42` and got `testing-hanoi-42` or rather 75ecbddc.

 [It looks better now :page_facing_up:](https://lorenz.leutgeb.xyz/tmp/hanoi-report.html). For the configurations

 1. `[default/naive/alpharoaming/NAIVE]` (14.48s)
 2. `[default/naive/alpharoaming/BERKMIN]` (1m20s)
 3. `[default/naive/alpharoaming/BERKMINLITERAL]` (16.52s)
 4. `[default/naive/naive/NAIVE]` (19.29s)

We get exactly on answer set that includes the previously problematic/missing facts `noWhere(0,2).` or `where(0,3)`.

Because of the strange result for `[default/naive/naive/DD]` (the answer set is printed, but the test times out nevertheless) I did a separate run. It took 3m33s. Maybe the system is taking *very* long to realize that there is no more choice to make, hence no other answer sets can be found? This is just a wild guess.

Other configurations time out after ~100s (19 in total) or have been skipped by me because I assumed that they will very likely time out as well. 

In 15 cases the timeout is reached at:

```
ChoiceManager.checkActiveChoicePoints(ChoiceManager.java:334)
ChoiceManager.isActiveChoiceAtom(ChoiceManager.java:304)
DependencyDrivenHeuristic.chooseAtom(DependencyDrivenHeuristic.java:199)
DefaultSolver.choose(DefaultSolver.java:343)
...
```

Two other runs are caught while propagating, another two on different traces in the heuristics.

**Comment by AntoniusW** [comment] 2017-12-11 21:47
I did some debugging with some of the slow/timeout instances and it seems to be the mbt-issue again. So, it looks like the original issue is gone and what we see now is actually another issue. Therefore, I am soon going to close this issue if no other arguments are brought up.

**Comment by AntoniusW** [comment] 2017-12-14 22:14
What was the question?

**Closed by AntoniusW** 2017-12-14 22:14 UTC
Labels: bug, solver
