### ISSUE TITLE
RuntimeException "Watch invariant violated" produced by HeadBodyTransformationTests

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#101] opened 2017-11-23 12:51 UTC
The following unit tests in `HeadBodyTransformationTests` (available on the [benchmarking-heads_bodies](https://github.com/alpha-asp/Alpha/blob/benchmarking-heads_bodies/src/test/java/at/ac/tuwien/kr/alpha/solver/HeadBodyTransformationTests.java) branch) produce `RuntimeException` with the message "Watch invariant violated! Should not happen":

- testProgramA_N2
- testProgramA_N4
- testProgramA_N8

Stack trace:

> java.lang.RuntimeException: Watch invariant violated! Should not happen.
> 	at at.ac.tuwien.kr.alpha.Util.oops(Util.java:84)
> 	at at.ac.tuwien.kr.alpha.solver.NoGoodStoreAlphaRoaming$WatchedNoGoodsChecker.checkOrdinaryWatchesInvariant(NoGoodStoreAlphaRoaming.java:724)
> 	at at.ac.tuwien.kr.alpha.solver.NoGoodStoreAlphaRoaming$WatchedNoGoodsChecker.doWatchesCheck(NoGoodStoreAlphaRoaming.java:655)
> 	at at.ac.tuwien.kr.alpha.solver.NoGoodStoreAlphaRoaming.backtrack(NoGoodStoreAlphaRoaming.java:83)
> 	at at.ac.tuwien.kr.alpha.solver.ChoiceManager.backtrack(ChoiceManager.java:266)
> 	at at.ac.tuwien.kr.alpha.solver.ChoiceManager.backtrackFast(ChoiceManager.java:232)
> 	at at.ac.tuwien.kr.alpha.solver.ChoiceManager.backjump(ChoiceManager.java:220)
> 	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.learnBackjumpAddFromConflict(DefaultSolver.java:203)
> 	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:130)
> 	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:31)
> 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
> 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
> 	at at.ac.tuwien.kr.alpha.solver.HeadBodyTransformationTests.test(HeadBodyTransformationTests.java:165)
> 	at at.ac.tuwien.kr.alpha.solver.HeadBodyTransformationTests.testProgramA_N8(HeadBodyTransformationTests.java:131)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
> 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by AntoniusW** [comment] 2017-11-23 12:57
That's serious. Can you extract (one of) those failing programs and put them here, so we can test it on master?

**Comment by AntoniusW** [comment] 2017-11-23 20:58
Confirmed. Investigating ...

**Comment by lorenzleutgeb** [comment] 2017-11-24 13:25
I did quite a lot of changes in #83 but hoped that our suite of unit tests would be enough to cover errors produced in such a refactoring. It would interesting to also run the tests before this refactoring took place.

**Comment by AntoniusW** [comment] 2017-11-24 14:15
Did not yet check if the problem occurs before #83, but I see how the error is happening. It is caused by two assignments on lower decision levels, that hit both watches of a nogood and do some propagation, then during fixing of the watches, propagation (\*) causes another conflict that leads to more backjumping and propagations. For some reason the watches then are pointing at wrong positions. I am not yet sure what the right fix for this is, but I think we have to modify both watches in one go if there was an assignment on a lower decision level, because after (\*) the second watch is at a wrong position.

**Comment by AntoniusW** [comment] 2017-11-24 15:53
The bug exists also with d76966ee, which is several days before #83. I guess it is a bug that has been there for quite some time.

**Closed** 2017-11-29 10:37 UTC
Labels: bug, solver
