### ISSUE TITLE
Fully support aggregates.

### ISSUE THREAD

**Issue by AntoniusW** [alpha-asp/Alpha#141] opened 2018-08-18 11:26 UTC
The current implementation of aggregates has some limitations. What is missing is:
 
- Default bound if none is given.
- Allow upper bounds and `=` for aggregates.
- Allow more than one aggregate per rule.
- Ensure the interval rewriting is compatible with the aggregate rewriting. A rule like
  `num(K) :-  K <= #count {X : value(X) }, K=1..4.` currently fails with uninformative errors.

**Comment by madmike200590** [comment] 2020-08-26 11:11
"Rewriting sketch" for `X = #count{...}` construct:

```
thing(1).
thing(2).
thing(3).

cnt_candidate(1).
cnt_candidate(2).
cnt_candidate(3).
cnt_candidate(4).
cnt_candidate(5).
cnt_candidate(6).

%cnt_things(X) :- X = #count{ N : thing(N)}.
cnt_things(X) :- leq_cnt_things(X), not leq_cnt_things(X + 1). % R1

leq_cnt_things(X) :- X <= #count{ N : thing(N)}, cnt_candidate(X). %R2

gt_cnt_things(X) :- cnt_candidate(X), not leq_cnt_things(X). %R3
```
**Problem**: we need the `cnt_candidate` predicate to bind X in rules R2 and R3, otherwise these rules aren't safe.

**Comment by madmike200590** [comment] 2020-08-26 15:12
In order to address the issue mentioned above (binding of `X` in R2), I got the following version (using enums) to work:
```
#enumeration_predicate_is cnt_enum.

thing(23..66).

%cnt_things(X) :- X = #count{ N : thing(N)}.
cnt_things(X) :- leq_cnt_things(X), not leq_cnt_things(X + 1).
cnt_candidate(I) :- thing(X), cnt_enum(cnt_candidates, X, I).
leq_cnt_things(X) :- X <= #count{ N : thing(N)}, cnt_candidate(X).
```
The predicate `cnt_candidate/1` roughly corresponds to `sorting_network_input_number/2` used by the current `CardinalityNormalization` transformation. This should probably be re-used when doing the actual implementation.

I found that the performance of this version is **extremely poor** (enormous heap usage while evaluating count aggregate) when stratified evaluation (see PR #207) is enabled. Will look into it.

**Comment by madmike200590** [comment] 2020-08-31 11:42
Update: I'm still looking into the above mentioned performance issues, findings from profiling so far:
In the variant with stratified evaluation, we use significantly more heap, even though roughly 25% of JVM runtime is spent in garbage collection (which is bad..).
The vast mahority of allocated and then quickly discarded objects are - both with and without stratified evaluation - `TreeMap`s, i.e. `Substitution`s. Since these are created within `LiteralInstantiator` (which is used both by `StratifiedEvaluation` and `NaiveGrounder`), my best guess for the significantly larger amount of objects created by `StratifiedEvaluation` is that the stratified evaluation algorithm takes significantly more iterations to solve the (fully stratifiable) program than the "default" workflow of `NaiveGrounder`. I'm investigating possible root causes.

Note that, in a later implementation stage, it might make sense to solve aggregates within stratifiable sub-programs natively in `StratifiedEvaluation`, only rewriting aggregates that cannot be solved by using stratified evaluation.

**Comment by rtaupe** [comment] 2020-09-09 14:46
If aggregates were handled directly by the solver in a special way instead of rewriting them, there might be better solutions.
For example: Wouldn´t it be possible to maintain the set of atoms occurring in the aggregate, and evaluate the aggregate function only when all of them are assigned (in case the result of the aggregate function is assigned to a variable, as in the `X = #count{...}` example)?

**Comment by AntoniusW** [comment] 2020-09-09 21:40
That observation by @rtaupe is correct. If evaluation of aggregates can be postponed until after all the atoms occurring in the aggregate are assigned, then evaluation of such an aggregate is very easy. If the aggregate, however, has an influence on whether an assignment is an answer-set, then things change. Consider, for example
```
:- not vals_match.
vals_match :- toMatch(X), X = #count{ Y : bar(Y) }.
{ bar(Y) } :- something(Y).
```
Obviously, evaluating the count after all relevant atoms are assigned is possible. This will, however, miss the opportunity to backtrack early on assignments, where there are more `bar`s than the value in `toMatch`. So, evaluating aggregates with special constructs should allow for partial evaluations (as rewriting can do out-of-the box).

Considering the late answer-set competitions, there are translational approaches that performed very well indeed (consider e.g. LP2NORMAL in the ASPCOMP2017).

In the end, it is a matter of time and knowledge -- if someone were to implement it in Alpha, I would be very happy. On the short run, using the normalization that is already there, likely provides a working implementation much earlier.

**Comment by madmike200590** [comment] 2020-09-14 14:29
Some updates:
The performance problem in `StratifiedEvaluation` was caused by an implementation bug and is now fixed in PR207.

The general workflow for aggregate rewriting as far as I sketched it out now is going to be:
* Step 1: Split aggregates with lower and upper bounds into separate aggregate literals with only one comparison operator
* Step 2: In a next transformation step, transform all aggregate literals, such that the only operators in use are `<=` and `=` (for which we already have working alternative encodings)
* Step 3: Rewrite remaining aggregate literals using existing alternative encodings

I have a draft implementation for the overall process as well as step 1 (literal splitting) ready - will create a draft PR shortly, as I think it makes more sense for everyone to be able to see the code so far.

Open issues on literal splitting - Suppose we have a rule:
```cnt_not_between(X, Y) :- dom1(X), dom2(Y), not X < #count{ N : stuff(N) } < Y```
Since according to the ASP Core2 Standard, aggregate literals may be negated, the rule is valid.
It should fire if, for given X, Y, |stuff(N)| is NOT in the open interval (X,Y).
The "naive" approach to splitting the aggregate literal is the following:
The atom `X < #count{ N : stuff(N) } < Y` becomes the two separate atoms `X < #count{ N : stuff(N) }, Y > #count{ N : stuff(N) }`.
This does not present an issue as long as the source literal is not negated - if the source literal is negated, we would need syntax to express the "compound" body literal `not (a1, a2)`, where a1 and a2 are atoms. Since such syntax is not part of the standard,
we need to introduce a new rule, i.e.
```cnt_not_between(X, Y) :- dom1(X), dom2(Y), not X < #count{ N : stuff(N) } < Y
==>
cnt_not_between(X, Y) :- dom1(X), dom2(Y), not _aggregate_output(count_1, result(X, Y)). % R1
_aggregate_output(count_1, result(X, Y)) :- X < #count{ N : stuff(N) }, Y > #count{ N : stuff(N) }. %R2
```
The problem with introducing that new rule is that, now, variables X and Y are not bound, although they were bound by literals `dom1(X)` and `dom2(Y)` in the initial rule, i.e. `R2` should really be:
```
_aggregate_output(count_1, result(X, Y)) :- X < #count{ N : stuff(N) }, Y > #count{ N : stuff(N) }, dom1(X), dom2(Y). %R2
```
Currently, for an aggregate literal `lit` of form `[not] VAR OP AGG`, `AggregateLiteral#getBindingVariables` returns `VAR` iff:
* `lit` is positive and `OP == "="`, or
* `lit` is negative and `OP == "!="`
.. which makes sense so far.

Based on the above definition of binding variables, generic splitting of an aggregate literal `aggLit` in a rule `r` should work as follows:
* Substitute `aggLit` in the body of `r` with a new basic atom `aggregate_output` of from `_aggregate_output(AGG_ID, AGGREGATE_VARS)`.
* Derive `aggregate_output` in a new rule `r_agg`. For all **non-binding** variables in `AGGREGATE_VARS`, add the body literals from `r` which bind the variables in question also to the body of `r_agg`.
In order to make this work, I need to change the implementation of `AggregateLiteral#getNonBindingVariables` (which currently throws an `UnsupportedOperationException`) to assume that every variable that is not binding is consequently non-binding.
@AntoniusW do you think this makes sense from a semantics point of view?

**Comment by AntoniusW** [comment] 2020-09-14 15:47
> However, there's still one open issue on literal splitting. Suppose we have a rule:
`cnt_not_between(X, Y) :- dom1(X), dom2(Y), not X < #count{ N : stuff(N) } < Y`
Since according to the ASP Core2 Standard, aggregate literals may be negated, the rule is valid.
It should fire if, for given X, Y, |stuff(N)| is NOT in the open interval (X,Y).
> The "naive" approach to splitting the aggregate literal is the following:
The atom `X < #count{ N : stuff(N) } < Y` becomes the two separate atoms `X < #count{ N : stuff(N) }, Y > #count{ N : stuff(N) }`.
This does not present an issue as long as the source literal is not negated - if the source literal is negated, we would need syntax to express the "compound" body literal `not (a1, a2)`, where a1 and a2 are atoms. 

As far as I understand the standard, in this case the whole rule is rewritten into two rules, with the same body, except one contains `not a1` and the other `not a2` (see Section 4, Aggregate Relations, page 8 of https://arxiv.org/pdf/1911.04326.pdf ).

Does this solve the problem or did I miss something?

**Comment by madmike200590** [comment] 2020-09-14 16:54
Thanks, I overlooked that! Yes, that should solve it, although I still think that the solution with the "intermediate rule" is the more elegant one. For now, I'll go along with the standard and implement it like that.

**Closed** 2021-09-16 11:54 UTC
Labels: preproc
